spring:
  cloud:
    nacos:
      server-addr: 192.168.64.129:8848 # Nacos server address
      username: nacos # Nacos username
      password: nacos # Nacos password
      discovery:
        namespace: dev
        group: DEFAULT_GROUP
      config:
        namespace: dev
        group: DEFAULT_GROUP